name: Check PR title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check PR title
        run: |
          title=$(echo "${{ github.event.pull_request.title }}" | tr -d '\r')
          if ! echo "${title}" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9]+\))?(!)?: [^[:punct:]]+(\n[A-Za-z0-9_ -]*#[0-9]+)?$"; then
            echo "ERROR: Pull request title does not follow Conventional Commit format. Please update the title." >&2
            exit 1
          fi
